# Generated by Django 4.2.1 on 2023-05-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(to='exercise.exercise'),
        ),
    ]
