# Generated by Django 4.2.1 on 2023-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('type', '0001_initial'),
        ('workout', '0003_remove_workout_media_workout_difficulty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='type',
        ),
        migrations.AddField(
            model_name='workout',
            name='inventory',
            field=models.ManyToManyField(to='equipment.equipment'),
        ),
        migrations.AddField(
            model_name='workout',
            name='type',
            field=models.ManyToManyField(to='type.type'),
        ),
    ]
