# Generated by Django 4.2.1 on 2023-05-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('difficulty', '0001_initial'),
        ('workout', '0004_remove_workout_inventory_remove_workout_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.ManyToManyField(to='difficulty.difficulty'),
        ),
    ]
