# Generated by Django 4.2.1 on 2023-05-29 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0003_remove_exercise_type_exercise_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=False, verbose_name='Дата')),
                ('time', models.TimeField(default=False, verbose_name='Время')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('workout', models.ManyToManyField(to='exercise.exercise')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
