# Generated by Django 4.2.1 on 2023-05-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Упражнение')),
                ('hardness', models.FloatField(default=False, verbose_name='Сложность')),
                ('amount', models.IntegerField(default=False, verbose_name='Кол-во повторений')),
                ('media', models.ImageField(default=False, upload_to='exercises/images', verbose_name='Изображение')),
                ('show_timer', models.BooleanField(default=False, verbose_name='Таймер')),
                ('calories', models.IntegerField(default=False, verbose_name='Калории')),
                ('equipment', models.IntegerField(default=False, verbose_name='Экипировка')),
            ],
            options={
                'verbose_name': 'Упражнение',
                'verbose_name_plural': 'Упражнения',
            },
        ),
    ]
