# Generated by Django 4.2.1 on 2023-05-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='hardness',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='show_timer',
        ),
        migrations.AddField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(default=False, verbose_name='Длительность'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.CharField(default=False, max_length=255, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='media',
            field=models.ImageField(default=False, upload_to='exercises/images', verbose_name='Медиа'),
        ),
    ]
