# Generated by Django 4.2.1 on 2023-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('type', '0001_initial'),
        ('exercise', '0002_remove_exercise_equipment_remove_exercise_hardness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.ManyToManyField(to='type.type'),
        ),
    ]
