# Generated by Django 4.2.1 on 2023-05-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('firstname', models.CharField(max_length=255, verbose_name='Имя')),
                ('avatar', models.ImageField(default=False, upload_to='users/avatars', verbose_name='Фото пользователя')),
                ('gender', models.BooleanField(default=False, verbose_name='Пол')),
                ('height', models.IntegerField(default=False, verbose_name='Рост')),
                ('weight', models.IntegerField(default=False, verbose_name='Вес')),
                ('age', models.IntegerField(default=False, verbose_name='Возраст')),
                ('preparation', models.FloatField(default=False, verbose_name='Уровень подготовки')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активирован')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Администратор')),
                ('is_client', models.BooleanField(default=False, verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
