# Generated by Django 4.2.1 on 2023-05-17 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_is_active_user_is_client_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=255, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=False, null=True, upload_to='user_image', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=255, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(max_length=255, null=True, verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preparation',
            field=models.FloatField(default=1.0, null=True, verbose_name='Подготовка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(max_length=255, null=True, verbose_name='Вес'),
        ),
    ]
