# Generated by Django 4.2.1 on 2023-05-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=False, upload_to='user_image', verbose_name='Аватар'),
        ),
    ]
