# Generated by Django 4.2.1 on 2023-05-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='target',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Цель'),
        ),
    ]
