# Generated by Django 4.2.1 on 2023-05-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gender', '0001_initial'),
        ('authentication', '0014_user_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.ManyToManyField(to='gender.gender'),
        ),
    ]
