# Generated by Django 4.2.1 on 2023-05-31 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
        migrations.RenameField(
            model_name='goal',
            old_name='user_id',
            new_name='user',
        ),
    ]
