# Generated by Django 4.2.1 on 2023-05-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название KPI')),
                ('calories', models.IntegerField(default=False, verbose_name='Калории')),
                ('type', models.CharField(max_length=255, verbose_name='Тип')),
                ('amount', models.IntegerField(default=False, verbose_name='Кол-во повторений')),
            ],
            options={
                'verbose_name': 'KPI',
                'verbose_name_plural': 'KPIs',
            },
        ),
    ]
